# permissions for end users to view sameruns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: samerun-viewer-role
rules:
- apiGroups:
  - program.projectsame.io
  resources:
  - sameruns
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - program.projectsame.io
  resources:
  - sameruns/status
  verbs:
  - get
