---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: cross-sell
  namespace: same-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/SAME-Project/example-kubeflow-CrossSell
---
apiVersion: program.projectsame.io/v1alpha1
kind: SameRun
metadata:
  name: cross-sell
  namespace: same-system
spec:
  interval: 1m0s
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: cross-sell
